name: SecurusExampleApp
options:
  bundleIdPrefix: com.securus.example
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
settings:
  base:
    SWIFT_VERSION: "5.10"
    GENERATE_INFOPLIST_FILE: false
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  SecurusExampleApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/*.plist"
    dependencies:
      - package: SecurusSDK
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.securus.example.app
        PRODUCT_NAME: "Securus Demo"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    info:
      path: Sources/Info.plist
      properties: {}
packages:
  SecurusSDK:
    path: ../SecurusSDK
schemes:
  SecurusExampleApp:
    build:
      targets:
        SecurusExampleApp: all
    run:
      config: Debug
      simulateLocation: false
    profile:
      config: Release
    analyze:
      config: Debug
